version: '3.8'

services:
  postgres:
    image: "postgres:11-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=price-stealer
      - POSTGRES_USER=price-stealer
      - POSTGRES_PASSWORD=price-stealer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U price-stealer"]
      interval: 10s
      timeout: 5s
      retries: 3

  price-stealer:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: "no"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/price-stealer
      SPRING_DATASOURCE_USERNAME: price-stealer
      SPRING_DATASOURCE_PASSWORD: price-stealer
#    networks: # Networks to join (Services on the same network can communicate with each other using their name)
#      - backend
#      - frontend